PATTERNS: dict[str, list[str]] = {
    "auth": ["jwt", "oauth", "session", "login", "password", "bcrypt"],
    "payments": ["stripe", "paypal", "checkout", "billing", "subscription"],
    "analytics": ["google-analytics", "mixpanel", "amplitude", "gtag"],
    "email": ["smtp", "sendgrid", "mailgun", "nodemailer"],
    "storage": ["s3", "firebase", "supabase", "cloudinary"],
    "cookies": ["cookie", "localStorage", "sessionStorage"],
    "geo": ["ip", "geolocation", "location"],
}

SKIP_DIRS: set[str] = {
    ".git",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "dist",
    "build",
    ".next",
    "target",
    "vendor",
    ".idea",
    ".vscode",
}

TEXT_EXTENSIONS: set[str] = {
    ".py",
    ".js",
    ".ts",
    ".tsx",
    ".jsx",
    ".go",
    ".rs",
    ".java",
    ".kt",
    ".rb",
    ".php",
    ".cs",
    ".swift",
    ".vue",
    ".svelte",
    ".astro",
    ".html",
    ".css",
    ".scss",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".xml",
    ".env",
    ".md",
    ".sql",
    ".graphql",
    ".prisma",
}

STACK_MARKERS: dict[str, list[str]] = {
    "Python": ["requirements.txt", "pyproject.toml", "Pipfile"],
    "Node.js": ["package.json"],
    "Go": ["go.mod"],
    "Rust": ["Cargo.toml"],
    "Ruby": ["Gemfile"],
    "PHP": ["composer.json"],
    "Java": ["pom.xml", "build.gradle"],
    "Docker": ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"],
    "Astro": ["astro.config.mjs", "astro.config.ts"],
    "Next.js": ["next.config.js", "next.config.mjs", "next.config.ts"],
    "Svelte": ["svelte.config.js", "svelte.config.ts"],
    "FastAPI": ["fastapi"],
    "Django": ["django"],
    "Rails": ["config/application.rb"],
}
